gratia/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

from django.conf .urls .static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('posts/',include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = "posts"

urlpatterns =[
    path('', views.posts_list, name="list"),

    path('<slug:slug>', views.post_page, name="page"),

]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    images = models.ImageField(blank=True)

def __str__(self):
    return self.title

gratia/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post':post})

posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}

        {{post.title}}

{% endblock  %}

{% block content %}

        

        <section class="mypost">
                        <h1>{{post.title}}</h1>
                        <p>{{post.body}}</p>
                        <p>{{post.slug}}</p>
                        <img src="{{post.images.url}}">
        </section>

{% endblock  %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Post
{% endblock  %}

{% block content %}
        <section class="mypost">

            {% for post in posts  %}
            
                <article >
                        <h2>
                            <a href="{% url 'posts:page' slug=post.slug %}">
                            {{post.title}}
                        </a>
                        
                        </h2>
                        <p>{{post.body}}</p>
                        <p>{{post.slug}}</p>
                        
                </article>
            
            {% endfor %}
        </section>

{% endblock  %}

templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock  %}

{% block content %}

{% endblock  %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock  %}

{% block content %}

{% endblock  %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
       {% block title %}
            Gratia
       {% endblock  %}
    </title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/main.js' %}" defer ></script>
   
</head>
<body>

    <nav>

        <ul  class="sidebar">
            <li onclick =" hideonclick()"><a href="#"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" 
                width="24px" fill="#000000"><path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/></svg></a></li>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="{% url "posts:list" %}">Posts</a></li>
        </ul>



        <ul>
            <li><a href="/">Gratia</a></li>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="{% url "posts:list" %}">Posts</a></li>

            <li onclick="showonclick()" ><a href="#"><svg xmlns="http://www.w3.org/2000/svg"
                 height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg></a></li>
        </ul>
    </nav>
    
    {% block content  %}
    
    
    {% endblock  %}

    
</body>
</html>